-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 15:26:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WebProducts
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WebProducts` ;

-- -----------------------------------------------------
-- Schema WebProducts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebProducts` DEFAULT CHARACTER SET utf8 ;
USE `WebProducts` ;

-- -----------------------------------------------------
-- Table `WebProducts`.`dialer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebProducts`.`dialer` ;

CREATE TABLE IF NOT EXISTS `WebProducts`.`dialer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NULL,
  `city` VARCHAR(45) NULL,
  `zip` INT NULL,
  `street` VARCHAR(95) NULL,
  `homenumber` INT NULL,
  `telnumber` VARCHAR(145) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebProducts`.`manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebProducts`.`manufacturer` ;

CREATE TABLE IF NOT EXISTS `WebProducts`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `homenumber` INT NULL,
  `zip` INT NULL,
  `city` VARCHAR(45) NULL,
  `telnumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebProducts`.`offers_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebProducts`.`offers_products` ;

CREATE TABLE IF NOT EXISTS `WebProducts`.`offers_products` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `offersname` VARCHAR(245) NULL,
  `offersprice` VARCHAR(245) NULL,
  `offerslink` VARCHAR(245) NULL,
  `offersdate` VARCHAR(45) NULL,
  `offersproperties` MEDIUMTEXT NULL,
  `offersimagelink` VARCHAR(45) NULL,
  `dialer_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  PRIMARY KEY (`productId`, `dialer_id`),
  INDEX `fk_offers_products_dialer_idx` (`dialer_id` ASC),
  INDEX `fk_offers_products_manufacturer1_idx` (`manufacturer_id` ASC),
  CONSTRAINT `fk_offers_products_dialer`
    FOREIGN KEY (`dialer_id`)
    REFERENCES `WebProducts`.`dialer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offers_products_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `WebProducts`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
